/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

/**
 *
 * @author agarw
 */
import Functionality.personDetails;
import Functionality.personDetailsDirectory;
import javax.swing.JPanel;
import Functionality.patientDetails;
import Functionality.patientDetailsDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
public class Edit_Patient extends javax.swing.JPanel {

    /**
     * Creates new form Add_Patient
     */
    private personDetails personDetails;
    JPanel jPanelContainer;
    private patientDetails patientDetails;
    private patientDetailsDirectory patientDirectory;
    private ViewPatientDetails viewPatientDetail;
    
    public Edit_Patient(patientDetailsDirectory dir, personDetails pd, JPanel container,ViewPatientDetails vpd ) {
        initComponents();
        this.personDetails = pd;
        this.jPanelContainer = container;
        this.patientDirectory = dir;
        this.viewPatientDetail = vpd;
        populateData();
        patientDetails = new patientDetails();
      //  patientDetails = new patientDetails();
        patientFirstNamejTxt.setText(personDetails.getFirstName());
        
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        patientFirstNamejTxt = new javax.swing.JTextField();
        patientIDjTxt = new javax.swing.JTextField();
        agejTxt = new javax.swing.JTextField();
        preferredPhajTxt = new javax.swing.JTextField();
        primaryDocjTxt = new javax.swing.JTextField();
        createPatientjBtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Patient First Name");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Age");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Patient ID");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Primary Doctor Name");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Preferred Pharmacy");

        createPatientjBtn.setBackground(new java.awt.Color(204, 204, 255));
        createPatientjBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        createPatientjBtn.setForeground(new java.awt.Color(0, 102, 102));
        createPatientjBtn.setText("Update Patient");
        createPatientjBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        createPatientjBtn.setBorderPainted(false);
        createPatientjBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createPatientjBtnActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(204, 204, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 102, 102));
        jButton2.setText("Back");
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Edit Patient Details");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(67, 67, 67)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(patientFirstNamejTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                            .addComponent(patientIDjTxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(agejTxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(primaryDocjTxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(preferredPhajTxt, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(288, 288, 288)
                        .addComponent(createPatientjBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(256, 256, 256)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(531, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jButton2)
                .addGap(5, 5, 5)
                .addComponent(jLabel7)
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientFirstNamejTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(patientIDjTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(agejTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(primaryDocjTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(preferredPhajTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(createPatientjBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(258, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void createPatientjBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createPatientjBtnActionPerformed
        // TODO add your handling code here:
        
         int counter = 0;
         if(personDetails.getFirstName().isEmpty() && patientIDjTxt.getText().isEmpty() && agejTxt.getText().isEmpty() 
                && primaryDocjTxt.getText().isEmpty() && preferredPhajTxt.getText().isEmpty()){
            
              JOptionPane.showMessageDialog(this,"Patient Details cannot be empty!");
        }
        else{
              // patientDetails = patientDirectory.addPatient();
        String patientFirstName = patientFirstNamejTxt.getText();//personDetails.getFirstname();
       // String patientLastName = personDetails.getLastName();
        String  patienID = patientIDjTxt.getText();
        
        
      
        
          if(Integer.parseInt(agejTxt.getText()) < 100 || Integer.parseInt(agejTxt.getText())!= 0){
              String patAge = agejTxt.getText();
          }
          else{
              counter++;
              JOptionPane.showMessageDialog(this,"Please enter valid age of patient!");
          }
        String priDocName = primaryDocjTxt.getText();
        String prePhar = preferredPhajTxt.getText();


        if(counter == 0){
             patientDetails.setPatientFirstName(patientFirstName);
      
        patientDetails.setDoctorName(priDocName);
        patientDetails.setPatientID(patienID);

        patientDetails.setPrefPharmacy(prePhar);
        personDetails.setPatientDetails(patientDetails);
        JOptionPane.showMessageDialog(null, "Patient Details updated successfully");
        
        
       // personDetails.setFirstname("");  
       
            patientIDjTxt.setText("");
            agejTxt.setText("");
            primaryDocjTxt.setText("");
            preferredPhajTxt.setText("");
        
         
        }

       
         }
      
        
        
        
      /* patientNameLbl.setVisible(false);
        patientIDLbl.setVisible(false);
        patientAgeLbl.setVisible(false);
        priDocNameLbl.setVisible(false);
        prePharLbl.setVisible(false);
        int i=0;
        String regex = "[a-zA-Z]+";
        String regexint = "[0-9]+";
        String patientName = patientNamejTxt.getText().trim();
        String patientId = patientIDjTxt.getText().trim();

        String primaryDocName= primaryDocjTxt.getText().trim();
        String preferPhar = preferredPhajTxt.getText().trim();
        if(patientName.matches(regex))
        {
            i++;
            personDeatils.setPatientName(patientName);
        }
        else
        {
            patientNameLbl.setVisible(true);
        }

        if(patientId.matches(regex))
        {
            i++;
            personDeatils.setPatientID(patientId);
        }
        else
        {
            patientIDLbl.setVisible(true);
        }

        try
        {
            int age = Integer.parseInt(agejTxt.getText().trim());
            if(String.valueOf(age).matches(regexint))
            {
                i++;
                personDeatils.setAge(age);
            }
            else
            {
                patientAgeLbl.setVisible(true);

            }
        }catch(NumberFormatException e)
        {
            patientAgeLbl.setVisible(true);
        }

        if(primaryDocName.matches(regex))
        {
            i++;
            personDeatils.setDoctorName(primaryDocName);
        }
        else
        {
            priDocNameLbl.setVisible(true);
        }
        if(preferPhar.matches(regex))
        {
            i++;
            personDeatils.setPrefPharmacy(preferPhar);
        }
        else
        {
            prePharLbl.setVisible(true);
        }
        if(i==5)
        {
            addVitalReadjBtn.setEnabled(true);
            createPatientjBtn.setEnabled(false);
            JOptionPane.showMessageDialog(null, "Patient Details created Successfully");
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Please Enter the details correctly");
        } */

    }//GEN-LAST:event_createPatientjBtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jPanelContainer.remove(this);
        viewPatientDetail.populateTable();
        CardLayout layout = (CardLayout)jPanelContainer.getLayout();
        layout.previous(jPanelContainer);
        
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField agejTxt;
    private javax.swing.JButton createPatientjBtn;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField patientFirstNamejTxt;
    private javax.swing.JTextField patientIDjTxt;
    private javax.swing.JTextField preferredPhajTxt;
    private javax.swing.JTextField primaryDocjTxt;
    // End of variables declaration//GEN-END:variables

    private void populateData() {
        patientIDjTxt.setText(personDetails.getPatientDetails().getPatientID());
        agejTxt.setText(String.valueOf(personDetails.getPatientDetails().getAge()));
        primaryDocjTxt.setText(personDetails.getPatientDetails().getDoctorName());
        preferredPhajTxt.setText(personDetails.getPatientDetails().getPrefPharmacy());
    }
}
