/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import java.awt.CardLayout;
import Functionality.personDetails;
import Functionality.personDetailsDirectory;
import javax.swing.JPanel;
import Functionality.patientDetailsDirectory;
import Functionality.vitalSignHistory;

/**
 *
 * @author agarw
 */
public class Health_Details extends javax.swing.JPanel {

    /**
     * Creates new form Health_Details
     */
    public JPanel jPanelContainer;
    public personDetails personDetails;
    //public personDetailsDirectory personDirectory;
    private patientDetailsDirectory patientDirectory;
   // private vitalSignHistory vitalHistory;
    
    public personDetailsDirectory personDirectory;
    
    public Health_Details(personDetailsDirectory pd,patientDetailsDirectory patientDirectory, JPanel container) {
        initComponents();
       // this.vitalHistory = new vitalSignHistory();
        this.personDirectory = pd;
        this.jPanelContainer = container;
        this.patientDirectory = patientDirectory;
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        viewDetailjBtn = new javax.swing.JButton();
        lblManagePerson = new javax.swing.JLabel();
        lblManagePerson1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 102, 153));

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Manage Person");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        viewDetailjBtn.setBackground(new java.awt.Color(204, 204, 255));
        viewDetailjBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        viewDetailjBtn.setText("Manage Patients");
        viewDetailjBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        viewDetailjBtn.setBorderPainted(false);
        viewDetailjBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDetailjBtnActionPerformed(evt);
            }
        });

        lblManagePerson.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblManagePerson.setForeground(new java.awt.Color(255, 255, 255));
        lblManagePerson.setText("Click here for person(s) information");

        lblManagePerson1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblManagePerson1.setForeground(new java.awt.Color(255, 255, 255));
        lblManagePerson1.setText("Click here for patient(s) information");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblManagePerson)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(146, 146, 146)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewDetailjBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblManagePerson1))
                .addContainerGap(158, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewDetailjBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblManagePerson)
                    .addComponent(lblManagePerson1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(327, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
      ViewPersonDetails vpd = new ViewPersonDetails(personDirectory,jPanelContainer);
        jPanelContainer.add("viewPersontable",vpd);
        CardLayout layout = (CardLayout)jPanelContainer.getLayout();
        layout.next(jPanelContainer);
      /*  Person_Profile per = new Person_Profile(personDirectory,jPanelContainer);
        jPanelContainer.add("PersonDetails", per);
        CardLayout layout = (CardLayout)jPanelContainer.getLayout();
        layout.next(jPanelContainer); */

    }//GEN-LAST:event_jButton1ActionPerformed

    private void viewDetailjBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDetailjBtnActionPerformed
        // TODO add your handling code here:
        ViewPatientDetails per = new ViewPatientDetails(personDirectory,jPanelContainer);
        jPanelContainer.add("patient", per);
        CardLayout layout = (CardLayout)jPanelContainer.getLayout();
        layout.next(jPanelContainer); 
      /*  ViewPatientDetails vpd = new ViewPatientDetails(personDirectory,jPanelContainer);
        jPanelContainer.add(vpd);
        CardLayout layout = (CardLayout)jPanelContainer.getLayout();
        layout.next(jPanelContainer);*/
    }//GEN-LAST:event_viewDetailjBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblManagePerson;
    private javax.swing.JLabel lblManagePerson1;
    private javax.swing.JButton viewDetailjBtn;
    // End of variables declaration//GEN-END:variables
}
