/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;
import Functionality.personDetails;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import Functionality.personDetailsDirectory;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
/**
 *
 * @author agarw
 */
public class Person_Profile extends javax.swing.JPanel {

    /**
     * Creates new form Person_Profile
     */
   // public personDetails personDetails;
    public personDetailsDirectory personDirectory;
    JPanel jpanelContainer;
    private ViewPersonDetails personDetails;
    
    public Person_Profile(personDetailsDirectory pd, JPanel container, ViewPersonDetails perdet) {
        initComponents();
        this.personDirectory = pd;
        this.jpanelContainer = container;
        this.personDetails = perdet;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        firstnamejTxt = new javax.swing.JTextField();
        lastNamejTxt = new javax.swing.JTextField();
        zipCodejTxt = new javax.swing.JTextField();
        streetadrjTxt = new javax.swing.JTextField();
        phonenumjTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        personCreatejBtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        dlCityName = new javax.swing.JComboBox<>();
        lblCityName = new javax.swing.JLabel();
        lblCommunityName = new javax.swing.JLabel();
        dlCommunityName = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(0, 102, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("First Name");

        zipCodejTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                zipCodejTxtKeyPressed(evt);
            }
        });

        phonenumjTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                phonenumjTxtKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Last Name");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Street Address");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Zip Code");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Phone Number");

        personCreatejBtn.setBackground(new java.awt.Color(204, 204, 255));
        personCreatejBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        personCreatejBtn.setForeground(new java.awt.Color(0, 102, 102));
        personCreatejBtn.setText("Add Person");
        personCreatejBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        personCreatejBtn.setBorderPainted(false);
        personCreatejBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personCreatejBtnActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Add Person Details");

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 102, 102));
        jButton1.setText("Back");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        dlCityName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Boston", "New York", "Los Angeles", "Chicago", "Houston", "Dallas", "San Jose", "Phoenix" }));

        lblCityName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCityName.setForeground(new java.awt.Color(255, 255, 255));
        lblCityName.setText("City Name");

        lblCommunityName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCommunityName.setForeground(new java.awt.Color(255, 255, 255));
        lblCommunityName.setText("Community Name");

        dlCommunityName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Community 1", "Community 2", "Community 3", "Community 4", "Community 5", " " }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(184, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblCityName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCommunityName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(firstnamejTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                    .addComponent(phonenumjTxt)
                    .addComponent(streetadrjTxt)
                    .addComponent(zipCodejTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                    .addComponent(lastNamejTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                    .addComponent(dlCityName, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dlCommunityName, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(342, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(271, 271, 271)
                .addComponent(personCreatejBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(29, 29, 29)
                .addComponent(jLabel9)
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(firstnamejTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lastNamejTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(phonenumjTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(streetadrjTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(zipCodejTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCityName)
                    .addComponent(dlCityName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dlCommunityName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCommunityName))
                .addGap(39, 39, 39)
                .addComponent(personCreatejBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void personCreatejBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personCreatejBtnActionPerformed
        // TODO add your handling code here:
        
        String firstName = null, lastName = null, streetAddress = null, cityName = null, communityName = null,zipCode = null, contactNum = null;
        boolean flag = false;
        if(firstnamejTxt.getText().isEmpty() || lastNamejTxt.getText().isEmpty() || lastNamejTxt.getText().isEmpty() 
                || streetadrjTxt.getText().isEmpty() || zipCodejTxt.getText().isEmpty() || phonenumjTxt.getText().isEmpty()){
            
              JOptionPane.showMessageDialog(this,"Person Details cannot be empty!");
        }
        else{
                personDetails personDetailsInner = personDirectory.addPerson();
                firstName = firstnamejTxt.getText();
                lastName = lastNamejTxt.getText();

                streetAddress = streetadrjTxt.getText();
                cityName = dlCityName.getSelectedItem().toString();
                communityName = dlCommunityName.getSelectedItem().toString();
                
                if (zipCodejTxt.getText().length() == 5){
                    zipCode = zipCodejTxt.getText();
                }
                else{
                    flag = true;
                    JOptionPane.showMessageDialog(null, "Please enter valid ZipCode!");
                }
                
                if (phonenumjTxt.getText().length() == 10){
                    contactNum = phonenumjTxt.getText();
                }
                else{
                    flag = true;
                    JOptionPane.showMessageDialog(null, "Please enter valid Contact Number!");
                }
                
                
           
                if(flag == false){
                    personDetailsInner.setFirstName(firstName);
                    personDetailsInner.setLastName(lastName);
                    personDetailsInner.setCityName(cityName);
                    personDetailsInner.setCommunityName(communityName);
                    personDetailsInner.setStreetAddress(streetAddress);
                    personDetailsInner.setZipCode(zipCode);
                    personDetailsInner.setPhoneNumber(contactNum);
               
               
                JOptionPane.showMessageDialog(null,"Person Details Created Successfully");
                
               firstnamejTxt.setText("");
               lastNamejTxt.setText("");
               streetadrjTxt.setText("");
               zipCodejTxt.setText("");
               phonenumjTxt.setText("");

        
               }
             
        }
      
    }//GEN-LAST:event_personCreatejBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jpanelContainer.remove(this);
        personDetails.generateTable();
        CardLayout layout = (CardLayout)jpanelContainer.getLayout();
        layout.previous(jpanelContainer);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void phonenumjTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phonenumjTxtKeyPressed
        // TODO add your handling code here:
        Character c =evt.getKeyChar();
        if(Character.isDigit(c) || Character.isISOControl(c)){
            phonenumjTxt.setEditable(true);
        }
        else
        {
            phonenumjTxt.setEditable(false);
        }
    }//GEN-LAST:event_phonenumjTxtKeyPressed

    private void zipCodejTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_zipCodejTxtKeyPressed
        // TODO add your handling code here:
        Character c =evt.getKeyChar();
        if(Character.isDigit(c) || Character.isISOControl(c)){
            zipCodejTxt.setEditable(true);
        }
        else
        {
            zipCodejTxt.setEditable(false);
        }
    }//GEN-LAST:event_zipCodejTxtKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> dlCityName;
    private javax.swing.JComboBox<String> dlCommunityName;
    private javax.swing.JTextField firstnamejTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lastNamejTxt;
    private javax.swing.JLabel lblCityName;
    private javax.swing.JLabel lblCommunityName;
    private javax.swing.JButton personCreatejBtn;
    private javax.swing.JTextField phonenumjTxt;
    private javax.swing.JTextField streetadrjTxt;
    private javax.swing.JTextField zipCodejTxt;
    // End of variables declaration//GEN-END:variables
}
