/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

/**
 *
 * @author agarw
 */
import Functionality.patientDetails;
import Functionality.personDetails;
import Functionality.personDetailsDirectory;
import java.awt.CardLayout;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

public class UpdatePersonDetails extends javax.swing.JPanel {

    /**
     * Creates new form UpdatePersonDetails
     */
    private personDetails personDetails;
    private JPanel jPanelContainer;
    private ViewPersonDetails viewPersonDetails;
    public UpdatePersonDetails(personDetails pd, JPanel panel, ViewPersonDetails vpd) {
        initComponents();
        this.personDetails = pd;
        this.jPanelContainer = panel;
        this.viewPersonDetails = vpd;
        populateData();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        firstnamejTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lastNamejTxt = new javax.swing.JTextField();
        streetadrjTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        phonenumjTxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        zipCodejTxt = new javax.swing.JTextField();
        updateDetailsjBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        dlCityName = new javax.swing.JComboBox<>();
        lblCityName = new javax.swing.JLabel();
        lblCommunityName = new javax.swing.JLabel();
        dlCommunityName = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(0, 102, 153));

        firstnamejTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstnamejTxtActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("First name");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Last name");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Street Address");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Zip Code");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Phone Number");

        zipCodejTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zipCodejTxtActionPerformed(evt);
            }
        });

        updateDetailsjBtn.setBackground(new java.awt.Color(204, 204, 255));
        updateDetailsjBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        updateDetailsjBtn.setForeground(new java.awt.Color(0, 102, 102));
        updateDetailsjBtn.setText("Update");
        updateDetailsjBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        updateDetailsjBtn.setBorderPainted(false);
        updateDetailsjBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateDetailsjBtnActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 102, 102));
        jButton1.setText("Back");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Update Person's Details");

        dlCityName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Boston", "New York", "Los Angeles", "Chicago", "Houston", "Dallas", "San Jose", "Phoenix" }));

        lblCityName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCityName.setForeground(new java.awt.Color(255, 255, 255));
        lblCityName.setText("City Name");

        lblCommunityName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCommunityName.setForeground(new java.awt.Color(255, 255, 255));
        lblCommunityName.setText("Community Name");

        dlCommunityName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Community 1", "Community 2", "Community 3", "Community 4", "Community 5", " " }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(firstnamejTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCityName, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCommunityName, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 227, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dlCommunityName, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(zipCodejTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                            .addComponent(streetadrjTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                            .addComponent(phonenumjTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                            .addComponent(dlCityName, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lastNamejTxt, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap(77, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(206, 206, 206)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(updateDetailsjBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(334, 334, 334))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel3)))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstnamejTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastNamejTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(phonenumjTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(streetadrjTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(zipCodejTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCityName)
                    .addComponent(dlCityName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dlCommunityName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCommunityName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(updateDetailsjBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void zipCodejTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zipCodejTxtActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_zipCodejTxtActionPerformed

    private void updateDetailsjBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateDetailsjBtnActionPerformed
        // TODO add your handling code here:
       // personDetails personDetails = personDirectory.addPerson();
       String zipCode = null, contactNum = null;
       int counter = 0;
        if(firstnamejTxt.getText().isEmpty() && lastNamejTxt.getText().isEmpty() && lastNamejTxt.getText().isEmpty() 
                && streetadrjTxt.getText().isEmpty() && zipCodejTxt.getText().isEmpty() && phonenumjTxt.getText().isEmpty()){
            
              JOptionPane.showMessageDialog(this,"Person Details cannot be empty!");
        }
        else{
            
                 if (zipCodejTxt.getText().length() == 5){
                    zipCode = zipCodejTxt.getText();
                }
                else{
                    counter++;
                    JOptionPane.showMessageDialog(null, "Please enter valid ZipCode!");
                }
                
                if (phonenumjTxt.getText().length() == 10){
                    contactNum = phonenumjTxt.getText();
                }
                else{
                    counter++;
                    JOptionPane.showMessageDialog(null, "Please enter valid Contact Number!");
                }
                
                
           
        }
        String firstName = firstnamejTxt.getText();
        String lastName = lastNamejTxt.getText();
       // String middleName = middileNamejTxt.getText();
       // String dateOfBirth = dateOfBirthjTxt.getText();
        String streetAddress = streetadrjTxt.getText();
       // String eMail = emailjTxt.getText();
        String cityName = dlCityName.getSelectedItem().toString();
        String communityName = dlCommunityName.getSelectedItem().toString();
       // int ssn = Integer.parseInt(ssnjTxt.getText());
        
        if(counter == 0){
        personDetails.setFirstName(firstName);
        personDetails.setLastName(lastName);
       // personDetails.setMiddleName(middleName);
       // personDetails.setEmailAddress(eMail);
       // personDetails.setDateOfBirth(dateOfBirth);
        personDetails.setPhoneNumber(contactNum);
        personDetails.setStreetAddress(streetAddress);
        personDetails.setZipCode(zipCode);
        personDetails.setCityName(cityName);
        personDetails.setCommunityName(communityName);
       // personDetails.setSsn(ssn);
        //Person_Details.
        JOptionPane.showMessageDialog(null,"Person Details Updated Successfully");
        
            firstnamejTxt.setText("");
               lastNamejTxt.setText("");
               lastNamejTxt.setText("");
               streetadrjTxt.setText("");
               zipCodejTxt.setText("");
               phonenumjTxt.setText("");
        }
                                   
    }//GEN-LAST:event_updateDetailsjBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jPanelContainer.remove(this);
        viewPersonDetails.generateTable();
        CardLayout layout = (CardLayout)jPanelContainer.getLayout();
        layout.previous(jPanelContainer);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void firstnamejTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstnamejTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnamejTxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> dlCityName;
    private javax.swing.JComboBox<String> dlCommunityName;
    private javax.swing.JTextField firstnamejTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField lastNamejTxt;
    private javax.swing.JLabel lblCityName;
    private javax.swing.JLabel lblCommunityName;
    private javax.swing.JTextField phonenumjTxt;
    private javax.swing.JTextField streetadrjTxt;
    private javax.swing.JButton updateDetailsjBtn;
    private javax.swing.JTextField zipCodejTxt;
    // End of variables declaration//GEN-END:variables

    private void populateData() {
        
    firstnamejTxt.setText(personDetails.getFirstName());
    lastNamejTxt.setText(personDetails.getLastName());
   
    streetadrjTxt.setText(personDetails.getStreetAddress());
    zipCodejTxt.setText(String.valueOf(personDetails.getZipCode()));
   
    phonenumjTxt.setText(String.valueOf(personDetails.getPhoneNumber()));
    dlCityName.setSelectedItem(personDetails.getCityName());
    dlCommunityName.setSelectedItem(personDetails.getCommunityName());
   
    }
}
